### ISSUE TITLE
Grooming: Sprint 2

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3772]
# Email/set

## User stories

As a user I want to....

 - Update Email Keyworkds (Duc)
 - Update Email mailboxIds (Lan)
 - Destroy emails (Rene) https://github.com/linagora/james-project/issues/3831

How to...

Implement https://jmap.io/spec-mail.html#emailset

# Read repair : mailbox & counters

(Benoit)

 - [x] https://github.com/linagora/james-project/issues/3815 `Read repair - mailbox`
 - [x] https://github.com/linagora/james-project/issues/3817 xx `Read repair - counters`
 - [x] https://github.com/apache/james-project/pull/248 ADR about applicative read repairs
 - [x] https://github.com/linagora/james-project/issues/3816 Documentation page - distributed James consistency model
    - Data Replication
        - Words about Cassandra consistency model
        - Words about ElasticSearch consistency model
    - De-normalization
        - Which data is denormalized ?
        - What can go wrong (denormalization inconsistencies) ?
        - `Solve Inconsistency tasks`
        - Applicative read repairs
    - Consistency across data stores
        - Write to object storage first, then position Cassandra meta-data
        - Cassandra <=> ElasticSearch: point to the EventBus (async, retries, dead-letter) + reIndex
        - Recovering RabbitMQ mailQueue from the Cassandra projection
 - [x] https://github.com/linagora/james-project/issues/3818 Review and merge https://github.com/linagora/james-project/pull/3635 ` POC Denormalize UidValidity as part of MailboxPath projection` 
 - [x] Deploy read repairs on DEV
 - [x] Deploy read repairs on openpaas.linagora.com
 - [x]  https://github.com/linagora/james-project/issues/3819 IMAP LIST should not query mailbox counters.

# Metrics: prometheus

 - Prepare presentation about prometheus
 - [x] TODO write a "linagora ADR" in `james-project-private` about fluentD
 - [x] TODO write a "linagora ADR" in `james-project-private` about prometheus

(Hai)

**Comment by chibenwa** [comment]
Remark: 
 - keywords / mailboxIds can either be "reset" or "partially updated"
 - DOD :
    - Share extension for mailboxIds
    - Updates for delegated mailboxes:  keyword, destroy don't need to care about it

We need to experiment an optimisation idea: When moving several messages, we can rely on the messageManager instead of the MessageIdManager.
 - We need to define a threshold from which this optimisation is worth it
 - we need the exact same patch to be specified for all messages, only concerning mailboxIds, single value reset
 - we need all the messages to be in a single mailbox
 - Use MessageManager::move
 - Track the number of DB calls, should reduce for high (10+) messages
 - timeboxed

read repairs unlocks uid-validity denormalisation performance enhancement

**Comment by chibenwa** [comment]
Hai will prepare a short presentation about prometheus

**Comment by chibenwa** [comment]
TODO write an ADR about read repairs

TODO write a "linagora ADR" in `james-project-private` about fluentD and prometheus.

**Comment by chibenwa** [comment]
Link to the board https://app.zenhub.com/workspaces/team-james-5873652b2a0b13cc0b8bbe63/board?milestones=Sprint%202%232020-10-30&filterLogic=any&repos=39182136,60690662,38885631,38827866,38827968,38828008,275764552&showPRs=false&showMilestones=false&showPipelineDescriptions=false&showEpics=false&showReleases=false
