### ISSUE TITLE
Account Delegation

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#3949]
- [x] We need a generic API answering the following question: (apache/james-project)
    - Can a user access this accountId ?
    - Which accountId can the user access ?
    - Provide a simple implementation where the user simply access his account.
 - [ ] apache james jmap rfc-8621 should rely on this interface for...
    - Session generation
    - Within the JMAP rfc-8621 routes (api, upload, dowload, etc...)
 - [x] Write an API in openpaas-james for delegation storage (who accesses what) + memory and contract
 - [x] Cassandra implementation of the storage API
 - [ ] Integration tests for delegation (including smoke testing executing the API, downloads, uploads, websocket, event-source)

We need:

 - [ ] To be able to list accounts I have access to (Improve DelegationStore API)
 - [ ] To have a JMAP extensions to:
    - [ ] Delegate my account to another people
    - [ ] Revoke delegation of my account on another people account (revoke a right given to me)
    - [ ] Revoke delegation of another people account on my account (revoke a right given to others)
    - [ ] Only the owner of the account should be able to interact with the delegation settings - you allow such checks it would be worthy to augment mailboxSession with an `actingUser` (optional field, by default the same than username) which our delegation JMAP methods could use....

 - [ ] Investigate https://datatracker.ietf.org/doc/draft-ietf-jmap-sharing/

**Comment by Arsnael** [comment]
Ok honestly I'm sorry I'm confused...

If we do an implementation in apache/james about which accountId can a user access (so a table storing this info right?), then isn't that more or less the delegation storage (who accesses what) already? I don't see in what it's different

**Comment by chibenwa** [comment]
s/implementation in apache/james about which accountId can a user access/API in apache/james about which accountId can a user access/g

That is not the same thing. Enabling is not doing.

Rationals is that the logic of "who can access what" is domain specific.

**Comment by Arsnael** [comment]
So on the apache project side it will just say I'm bob and I can only access Bob accountId then, correct?

**Comment by chibenwa** [comment]
> So on the apache project side it will just say I'm bob and I can only access Bob accountId then, correct?

Yes

**Comment by chibenwa** [comment]
Grooming notes on JMAP specifications for delegation: (could be changed, vocabulary SHOULD be refined)

```
Delegate (somebody able to access your account)

Delegate/get
Delegate/set (create, delete) 


DelegatedAccount (Accounts delegated to me)

SharedAccount/get (also shown in session object)
SharedAccount/set delete 


query? => Not needed because no search, because we expect the count of delegations to keep being small.
change? => not needed either ? We could likely just fetch it upon f5 when getting the session. 
```

**Comment by chibenwa** [comment]
## Ticket Split

 - [ ] Documentation (IE james specific extension)
 
 - [ ] Delegation store should allow listing accounts delegated to me
 - [ ] MailboxSession should have a `loggedInUser` set to the loggedIn user
 
 - [ ] Delegate/SharedAccount extension capability object
 - [ ] Delegate/get
 - [ ] Delegate/set create
 - [ ] Delegate/set delete
 - [ ] DelegatedAccount / get
 - [ ] DelegatedAccount / set delete
 - [ ] Show the list of accounts being delegated accounts in JMAP session
 
 - [ ] Delegation on JMAP endpoints (API, eventsource, websocket, download, uploads, etc.. all of them)
   Use of accountIds of delegated accounts
   (Can be further split - should not forget TMail endpoints?)

**Comment by quantranhong1999** [comment]
Rethink about `DelegatedAccount / set delete` and `Delegate/set delete`. I think this delegate/delegated accounts should be a JMAP `singleton` object for each account and therefore we should use `set update` instead.

**Comment by Arsnael** [comment]
Related to the ids perhaps?

**Comment by Arsnael** [comment]
Hmmm maybe you are right... worth the reflection 

I agree that I'm trying to write the jmap method tickets and I feel odd with the ids as well. The list of authorized users being represented as a frozen set in the user table could be interpreted as a singleton as well indeed

Will stop writing those tickets then until we decide ^^'

**Comment by chibenwa** [comment]
> l. The list of authorized users being represented as a frozen set in the user table could be interpreted as a singleton as well indeed

This set is not frozen, you can add-remove things in it

```
    public Mono<Void> addAuthorizedUsers(Username baseUser, Username userWithAccess) {
        return executor.executeVoid(addAuthorizedUsersStatement.bind()
            .setString(NAME, baseUser.asString())
            .setSet(AUTHORIZED_USERS, ImmutableSet.of(userWithAccess.asString()), String.class));
    }

    public Mono<Void> removeAuthorizedUser(Username baseUser, Username userWithAccess) {
        return executor.executeVoid(removeAuthorizedUsersStatement.bind()
            .setString(NAME, baseUser.asString())
            .setSet(AUTHORIZED_USERS, ImmutableSet.of(userWithAccess.asString()), String.class));
    }
```

A singleton enforces a set, reset logic while we already have support for the add, remove, list semantice at the storage / DB level.

I hardly can see the benefits of the singleton here.

**Comment by Arsnael** [comment]
What should be the ids then? We need to go fetch the account ids of each username present in that list?

**Comment by chibenwa** [comment]
Id could be hash based on the address ; it is a non problem IMO.
