### ISSUE TITLE
JMAP PushSubscription

### ISSUE THREAD

**Issue by Arsnael** [linagora/james-project#4403]
Subparts:

- [x] Write an Apacha James ADR
- [ ] API / contract / memory / cassandra
- [ ] JMAP methods (classic /get /set)
- [ ] encryption part
- [ ] webPushClient (send content, pool of HTTP clients)
- [ ] listener
- [ ] JMAP methods sided effects (validation code)
- [ ] Web push integration tests

**Comment by chibenwa** [comment]
ADR https://github.com/apache/james-project/pull/701
