### ISSUE TITLE
[EPIC] [RGDP] Endpoint to delete all user data

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#4755]
## Why ?

As part of B2C SaaS offerings, one need to be able to easily delete user data upon request.

We thus need to introduce a endpoint in James to do so.

# What ?

This would need to be a modular task (similar to user name change), as james is a modular product, and that user data is product specific.

 - [x] [Task skeleton + Webadmin](https://github.com/linagora/james-project/issues/4782) **Quan**

We would need to delete things linked to a user that qualifies as personnal data:

 - [x] [Delete all mailboxes thus emails + ACL + subscription](https://github.com/linagora/james-project/issues/4784) **Quan**
 - [x] [Delete filters](https://github.com/linagora/james-project/issues/4785) **Quan**
 - [x] [Delete vacation settings](https://github.com/linagora/james-project/issues/4786) **Quan**
 - [x] [Delegation](https://github.com/linagora/james-project/issues/4787) **Quan**
 - [x] [Web Push registration](https://github.com/linagora/james-project/issues/4788) **Quan**
 - [x] [Identity](https://github.com/linagora/james-project/issues/4789) **Quan**

In TMail:

 - [x] [Auto-complete databases](https://github.com/linagora/tmail-backend/issues/666) **Quan**
 - [x] [PGP public keys](https://github.com/linagora/tmail-backend/issues/667) **Quan**
 - [x] [Firebase registration](https://github.com/linagora/tmail-backend/issues/668) **Quan**

 - [x] AND add a way to delete all data belonging to a domain **Quan**
       -> Should have an option to delete data of all users of a domain (e.g a domain resigns from SaaS offer) in https://github.com/linagora/james-project/issues/4782
 - [x] Investigate Bayes DB management options in Rspamd **Quan**
       -> Reset statistic only available for all, not per user.

Additionally:

 - [x] [ADR](https://github.com/linagora/james-project/issues/4783) **Quan**

**Comment by Arsnael** [comment]
Add a step for RRTs
