### ISSUE TITLE
[STORY] JAMES-4025 Remove JMAP draft

### ISSUE THREAD

**Issue by chibenwa** [linagora/james-project#5147]
- [ ] [Rewrite existing tests on top of JMAP RFC-8621](https://github.com/linagora/james-project/issues/5151). This include:
    - [ ] VacationRelayIntegrationTest
    - [ ] VacationIntegrationTest
    - [ ] QuotaMailingTest
    - [ ] CorsHeaderAPITest
    - [ ] ImapSetMessagesMailboxesUpdatesCompatibility.feature (plain scala is OK)
    - [ ] ImapKeywordsConsistency.feature (plain scala is OK)

 - [ ] [Relocation of JMAP draft resources used bu JMAP RFC-8621](https://github.com/linagora/james-project/issues/5152)

 - [ ] [Dropping of the code](https://github.com/linagora/james-project/issues/5153)

- [ ] [Rewrite existing tests on top of JMAP RFC-8621 - webadmin-integration-test-common ](https://github.com/linagora/james-project/issues/5156)
Could be part of a polish sprint.

**Comment by Arsnael** [comment]
Do we replan soon to drop openpaas inbox on lng prod then? (hard to do this removal without it)

**Comment by vttranlina** [comment]
>  Relocation of JMAP draft resources used bu JMAP RFC-8621

first in my head

- [ ] PopulateEmailQueryViewListener

**Comment by chibenwa** [comment]
> Do we replan soon to drop openpaas inbox on lng prod then? (hard to do this removal without it)

Already done?

**Comment by Arsnael** [comment]
I do not remember seeing a mail or message with the confirmation that it was done but ok, great :)

**Comment by vttranlina** [comment]
I just created a tasks for 
- https://github.com/linagora/james-project/issues/5156
